### ISSUE TITLE
Build on Android

### ISSUE THREAD

**Issue by hashmap** [i1skn/ironbelly#5]

**Comment by liamaharon** [comment]
If this isn't already being worked on I'd like to take a crack. 

Using [Parity Signer](https://github.com/paritytech/parity-signer) as a reference.

**Comment by i1skn** [comment]
Hi Liam, you can go ahead, AFAIK nobody is working on it right now!
Let me know if you have any questions! Thanks!

**Comment by liamaharon** [comment]
Using the Parity Signer repo as a reference (linked in prev comment) and these Medium posts [[1](https://medium.com/@marekkotewicz/building-a-mobile-app-in-rust-and-react-native-part-1-project-setup-b8dbcf3f539f), [2](https://medium.com/@marekkotewicz/building-a-mobile-app-in-rust-and-react-native-part-2-hello-world-60970a7d194a)], I've had partial success but have hit a wall, unable to get some of the dependencies to compile. 

Specifically having any of these deps enabled cause the build to fail with [this error](https://pastebin.com/EqpXYrZj) 
- cursive
- grin_wallet
- grin_core
- grin_util
- grin_keychain

The same issue occurs when trying to add the above dependencies to [this](https://github.com/Terrahop/react-native-rust-demo) boilerplate, which otherwise I was able to successfully build and run on an emulator.


I'm by no means experienced in this area, so not sure exactly what's going wrong but it appears that the compiler is trying to compile some C/C++ but can't find the required tool to compile it for Android, does that sound right? Hoping some experienced eyes will be able to pinpoint the issue better than I can.

If you'd like to try youself
- clone my branch https://github.com/liamaharon/ironbelly/tree/feature/build-android
- install the dependencies listed [here](https://github.com/paritytech/parity-signer#build-it)
- run
```bash
npm install

./setup_linux.sh

echo "ndk.dir=$NDK_HOME" > android/local.properties
echo "sdk.dir=$ANDROID_HOME" >> android/local.properties

cd rust/ironbelly_wallet
make android
```

**Comment by e-max** [comment]
It's hard to say but it seems that it failed trying to build liblmdb. Do you have this library properly installed? And headers and so on?

**Comment by liamaharon** [comment]
I believe I have liblmdb installed

Running `dpkg -l liblmdb-dev` outputs
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version         Architecture    Description
+++-====================-===============-===============-=============================================
ii  liblmdb-dev:amd64    0.9.21-1        amd64           Lightning Memory-Mapped Database development 
```

and `dpkg -L liblmdb-dev`
```
/.
/usr
/usr/include
/usr/include/lmdb.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/liblmdb.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/lmdb.pc
/usr/share
/usr/share/doc
/usr/share/doc/liblmdb-dev
/usr/share/doc/liblmdb-dev/copyright
/usr/lib/x86_64-linux-gnu/liblmdb.so
/usr/share/doc/liblmdb-dev/changelog.Debian.gz
```

if it helps, I'm also able to compile the grin node/wallet from source

**Comment by Daniel-Wang** [comment]
@i1skn From your [picture](https://twitter.com/i1skn/status/1152986124937302016) looks like you got the Android compilation to work, mind adding any build instructions and solutions for us?

**Comment by i1skn** [comment]
@Daniel-Wang it is still very messy process how I do it now and I would need to have some clean-up before. Also I'm not sure how to properly address the issue here: https://medium.com/@trustwallet/why-open-sourcing-android-app-could-be-a-harm-to-the-crypto-community-fb3ae1707dc6.

**Comment by Daniel-Wang** [comment]
@i1skn, that's a very valid problem. I think you should ask the broader community though about close sourcing Android due to fraud and scam clones. 

Another idea is to close source just the client code. The build process for Rust on Android I think is still valuable to be transparent for the Grin wallet community and users. @hashmap @liamaharon thoughts?

**Comment by liamaharon** [comment]
@i1skn I agree with @Daniel-Wang, would be great to get the build steps published somewhere once you've cleaned it up.

**Comment by i1skn** [comment]
@Daniel-Wang I've opened Android part a while ago and today bumped it to `grin-wallet#3.0.0` . For the implementation details look [here](https://github.com/i1skn/ironbelly/tree/master/rust). I'm closing this one then.
